version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: goggles/server:https
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"

  compromised:
    build:
      context: .
      dockerfile: Dockerfile.compromised
    depends_on:
      - server
    image: goggles/compromised:https

  benign:
    build:
      context: .
      dockerfile: Dockerfile.benign
    depends_on:
      - server
    image: goggles/benign

  detector:
    build:
      context: .
      dockerfile: Dockerfile.detector
    depends_on:
        - server
    image: goggles/detector
    volumes:
       - ./tcpdump:/tcpdump
    network_mode: "host"
    cap_add:
      - 'NET_RAW'
      - 'NET_ADMIN'

  tcpdump:
     image: kaazing/tcpdump
     network_mode: "host"
     volumes:
       - ./tcpdump:/tcpdump

networks:
  default:
    name: botnet
    ipam:
      config:
      - subnet: 172.18.0.0/16
    driver_opts:
      com.docker.network.bridge.name: botnet
